apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  back-office-visits
  template:
    metadata:
      labels:
        app:  back-office-visits
    spec:
      containers:
      - name: back-office-visits
        image: 0536654467/pulse-monitoring-back-office-visits
        env: 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pulse-monitoring-secret
                key: postgresPassword
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: pulse-monitoring-config
                key: postgresDataBase
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: pulse-monitoring-config
                key: postgresHost
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              secretKeyRef:
                name: pulse-monitoring-config
                key: springProfilesActive
        ports:
              - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: back-office-visits
spec:
  selector:
    app:  back-office-visits
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  8080 